//! Desktop WebJS sidecar contract types.
//!
//! The crate keeps Electron/WebJS-facing JSON frames separate from business
//! crates. M1 only models the sidecar initialization and readiness contract.

#![forbid(unsafe_code)]

use serde::{Deserialize, Serialize};
use std::fmt;
use thiserror::Error;

/// Errors returned when desktop sidecar contract values fail validation.
///
/// # Examples
///
/// ```
/// use opencode_desktop::{ServerReadyData, SidecarContractError};
///
/// let result = ServerReadyData::new("", "opencode", "secret");
/// assert!(matches!(result, Err(SidecarContractError::EmptyField { .. })));
/// ```
#[derive(Debug, Error, Eq, PartialEq)]
pub enum SidecarContractError {
    /// A required text field was empty after trimming.
    #[error("desktop sidecar field cannot be empty: {field}")]
    EmptyField {
        /// Contract field that failed validation.
        field: &'static str,
    },
    /// SQLite migration progress was outside the inclusive 0..=100 range.
    #[error("desktop sidecar migration progress must be between 0 and 100")]
    ProgressOutOfRange,
}

/// Initialization step emitted by the desktop sidecar startup flow.
///
/// # Examples
///
/// ```
/// use opencode_desktop::InitStep;
///
/// assert_eq!(InitStep::ServerWaiting.as_str(), "server_waiting");
/// ```
#[derive(Clone, Copy, Debug, Deserialize, Eq, PartialEq, Serialize)]
#[serde(rename_all = "snake_case")]
pub enum InitStep {
    /// The desktop shell is waiting for the Rust server to listen.
    ServerWaiting,
    /// The desktop shell is waiting for SQLite migration work to finish.
    SqliteWaiting,
    /// Initialization is complete and the renderer may load.
    Done,
}

impl InitStep {
    /// Returns the preload-compatible initialization step label.
    ///
    /// # Examples
    ///
    /// ```
    /// use opencode_desktop::InitStep;
    ///
    /// assert_eq!(InitStep::Done.as_str(), "done");
    /// ```
    #[must_use]
    pub const fn as_str(self) -> &'static str {
        match self {
            Self::ServerWaiting => "server_waiting",
            Self::SqliteWaiting => "sqlite_waiting",
            Self::Done => "done",
        }
    }
}

/// Ready payload returned by desktop `awaitInitialization()`.
///
/// The password is intentionally redacted from [`Debug`] output so desktop logs
/// can include the ready payload without leaking Basic Auth credentials.
///
/// # Examples
///
/// ```
/// use opencode_desktop::{ServerReadyData, SidecarContractError};
///
/// let ready = ServerReadyData::new("http://127.0.0.1:4096", "opencode", "secret")?;
/// assert_eq!(ready.username(), "opencode");
/// # Ok::<(), SidecarContractError>(())
/// ```
#[derive(Clone, Eq, PartialEq, Serialize)]
pub struct ServerReadyData {
    url: Box<str>,
    username: Box<str>,
    password: Box<str>,
}

impl ServerReadyData {
    /// Creates a validated sidecar ready payload.
    ///
    /// # Errors
    ///
    /// Returns [`SidecarContractError::EmptyField`] when any required field is
    /// empty after trimming whitespace.
    ///
    /// # Examples
    ///
    /// ```
    /// use opencode_desktop::{ServerReadyData, SidecarContractError};
    ///
    /// let ready = ServerReadyData::new("http://127.0.0.1:4096", "opencode", "secret")?;
    /// assert_eq!(ready.url(), "http://127.0.0.1:4096");
    /// # Ok::<(), SidecarContractError>(())
    /// ```
    pub fn new(
        url: impl Into<Box<str>>,
        username: impl Into<Box<str>>,
        password: impl Into<Box<str>>,
    ) -> Result<Self, SidecarContractError> {
        let url = require_non_empty("url", url.into())?;
        let username = require_non_empty("username", username.into())?;
        let password = require_non_empty("password", password.into())?;

        Ok(Self {
            url,
            username,
            password,
        })
    }

    /// Returns the HTTP endpoint URL used by the WebJS SDK client.
    ///
    /// # Examples
    ///
    /// ```
    /// # use opencode_desktop::{ServerReadyData, SidecarContractError};
    /// # let ready = ServerReadyData::new("http://127.0.0.1:4096", "opencode", "secret")?;
    /// assert_eq!(ready.url(), "http://127.0.0.1:4096");
    /// # Ok::<(), SidecarContractError>(())
    /// ```
    #[must_use]
    pub fn url(&self) -> &str {
        &self.url
    }

    /// Returns the Basic Auth username generated by the desktop shell.
    ///
    /// # Examples
    ///
    /// ```
    /// # use opencode_desktop::{ServerReadyData, SidecarContractError};
    /// # let ready = ServerReadyData::new("http://127.0.0.1:4096", "opencode", "secret")?;
    /// assert_eq!(ready.username(), "opencode");
    /// # Ok::<(), SidecarContractError>(())
    /// ```
    #[must_use]
    pub fn username(&self) -> &str {
        &self.username
    }

    /// Returns the Basic Auth password for SDK initialization.
    ///
    /// # Examples
    ///
    /// ```
    /// # use opencode_desktop::{ServerReadyData, SidecarContractError};
    /// # let ready = ServerReadyData::new("http://127.0.0.1:4096", "opencode", "secret")?;
    /// assert_eq!(ready.password(), "secret");
    /// # Ok::<(), SidecarContractError>(())
    /// ```
    #[must_use]
    pub fn password(&self) -> &str {
        &self.password
    }
}

impl fmt::Debug for ServerReadyData {
    fn fmt(&self, formatter: &mut fmt::Formatter<'_>) -> fmt::Result {
        formatter
            .debug_struct("ServerReadyData")
            .field("url", &self.url)
            .field("username", &self.username)
            .field("password", &"<redacted>")
            .finish()
    }
}

impl<'de> Deserialize<'de> for ServerReadyData {
    fn deserialize<Deserializer>(deserializer: Deserializer) -> Result<Self, Deserializer::Error>
    where
        Deserializer: serde::Deserializer<'de>,
    {
        let wire = ServerReadyDataWire::deserialize(deserializer)?;
        Self::new(wire.url, wire.username, wire.password).map_err(serde::de::Error::custom)
    }
}

#[derive(Deserialize)]
struct ServerReadyDataWire {
    url: Box<str>,
    username: Box<str>,
    password: Box<str>,
}

/// Validated SQLite migration progress percentage for sidecar events.
///
/// # Examples
///
/// ```
/// use opencode_desktop::{MigrationProgress, SidecarContractError};
///
/// let progress = MigrationProgress::try_from(42)?;
/// assert_eq!(progress.as_percent(), 42);
/// # Ok::<(), SidecarContractError>(())
/// ```
#[derive(Clone, Copy, Debug, Deserialize, Eq, PartialEq, Serialize)]
#[serde(try_from = "u8", into = "u8")]
pub struct MigrationProgress(u8);

impl MigrationProgress {
    /// Returns the progress value as an integer percentage.
    ///
    /// # Examples
    ///
    /// ```
    /// use opencode_desktop::{MigrationProgress, SidecarContractError};
    ///
    /// let progress = MigrationProgress::try_from(100)?;
    /// assert_eq!(progress.as_percent(), 100);
    /// # Ok::<(), SidecarContractError>(())
    /// ```
    #[must_use]
    pub const fn as_percent(self) -> u8 {
        self.0
    }
}

impl TryFrom<u8> for MigrationProgress {
    type Error = SidecarContractError;

    fn try_from(value: u8) -> Result<Self, Self::Error> {
        if value <= 100 {
            Ok(Self(value))
        } else {
            Err(SidecarContractError::ProgressOutOfRange)
        }
    }
}

impl From<MigrationProgress> for u8 {
    fn from(value: MigrationProgress) -> Self {
        value.0
    }
}

/// Redacted sidecar error message safe to pass across the desktop boundary.
///
/// # Examples
///
/// ```
/// use opencode_desktop::{SidecarContractError, SidecarErrorMessage};
///
/// let message = SidecarErrorMessage::new("startup failed")?;
/// assert_eq!(message.as_str(), "startup failed");
/// # Ok::<(), SidecarContractError>(())
/// ```
#[derive(Clone, Debug, Eq, PartialEq, Serialize)]
#[serde(transparent)]
pub struct SidecarErrorMessage(Box<str>);

impl SidecarErrorMessage {
    /// Creates a sidecar error message after validating it is not empty.
    ///
    /// # Errors
    ///
    /// Returns [`SidecarContractError::EmptyField`] when the message is empty
    /// after trimming whitespace.
    ///
    /// # Examples
    ///
    /// ```
    /// use opencode_desktop::{SidecarContractError, SidecarErrorMessage};
    ///
    /// let message = SidecarErrorMessage::new("startup failed")?;
    /// assert_eq!(message.as_str(), "startup failed");
    /// # Ok::<(), SidecarContractError>(())
    /// ```
    pub fn new(error: impl Into<Box<str>>) -> Result<Self, SidecarContractError> {
        require_non_empty("error", error.into()).map(Self)
    }

    /// Returns the redacted error message.
    ///
    /// # Examples
    ///
    /// ```
    /// use opencode_desktop::{SidecarContractError, SidecarErrorMessage};
    ///
    /// let message = SidecarErrorMessage::new("startup failed")?;
    /// assert_eq!(message.as_str(), "startup failed");
    /// # Ok::<(), SidecarContractError>(())
    /// ```
    #[must_use]
    pub fn as_str(&self) -> &str {
        &self.0
    }
}

impl<'de> Deserialize<'de> for SidecarErrorMessage {
    fn deserialize<Deserializer>(deserializer: Deserializer) -> Result<Self, Deserializer::Error>
    where
        Deserializer: serde::Deserializer<'de>,
    {
        let error = Box::<str>::deserialize(deserializer)?;
        Self::new(error).map_err(serde::de::Error::custom)
    }
}

/// Sidecar event frame sent from Rust sidecar to Electron main process.
///
/// # Examples
///
/// ```
/// use opencode_desktop::{ServerReadyData, SidecarContractError, SidecarEvent};
///
/// let ready = ServerReadyData::new("http://127.0.0.1:4096", "opencode", "secret")?;
/// let event = SidecarEvent::ready(ready);
/// assert_eq!(event.event_type(), "ready");
/// # Ok::<(), SidecarContractError>(())
/// ```
#[derive(Clone, Debug, Deserialize, Eq, PartialEq, Serialize)]
#[serde(tag = "type", rename_all = "snake_case")]
pub enum SidecarEvent {
    /// The Rust sidecar has bound the HTTP server and is ready.
    Ready {
        /// Ready payload consumed by desktop `awaitInitialization()`.
        data: ServerReadyData,
    },
    /// SQLite migration progress update.
    Sqlite {
        /// Migration percentage between 0 and 100.
        progress: MigrationProgress,
    },
    /// The sidecar stopped cleanly.
    Stopped,
    /// The sidecar failed before it could become ready.
    Error {
        /// Redacted error message safe for desktop logs.
        error: SidecarErrorMessage,
    },
}

impl SidecarEvent {
    /// Creates a sidecar ready event.
    ///
    /// # Examples
    ///
    /// ```
    /// use opencode_desktop::{ServerReadyData, SidecarContractError, SidecarEvent};
    ///
    /// let ready = ServerReadyData::new("http://127.0.0.1:4096", "opencode", "secret")?;
    /// let event = SidecarEvent::ready(ready);
    /// assert_eq!(event.event_type(), "ready");
    /// # Ok::<(), SidecarContractError>(())
    /// ```
    #[must_use]
    pub const fn ready(data: ServerReadyData) -> Self {
        Self::Ready { data }
    }

    /// Creates a validated SQLite migration progress event.
    ///
    /// # Errors
    ///
    /// Returns [`SidecarContractError::ProgressOutOfRange`] when progress is
    /// greater than 100.
    ///
    /// # Examples
    ///
    /// ```
    /// use opencode_desktop::{SidecarContractError, SidecarEvent};
    ///
    /// let event = SidecarEvent::sqlite(75)?;
    /// assert_eq!(event.event_type(), "sqlite");
    /// # Ok::<(), SidecarContractError>(())
    /// ```
    pub fn sqlite(progress: u8) -> Result<Self, SidecarContractError> {
        Ok(Self::Sqlite {
            progress: MigrationProgress::try_from(progress)?,
        })
    }

    /// Creates a stopped event.
    ///
    /// # Examples
    ///
    /// ```
    /// use opencode_desktop::SidecarEvent;
    ///
    /// let event = SidecarEvent::stopped();
    /// assert_eq!(event.event_type(), "stopped");
    /// ```
    #[must_use]
    pub const fn stopped() -> Self {
        Self::Stopped
    }

    /// Creates a redacted error event.
    ///
    /// # Examples
    ///
    /// ```
    /// use opencode_desktop::{SidecarContractError, SidecarEvent};
    ///
    /// let event = SidecarEvent::error("startup failed")?;
    /// assert_eq!(event.event_type(), "error");
    /// # Ok::<(), SidecarContractError>(())
    /// ```
    ///
    /// # Errors
    ///
    /// Returns [`SidecarContractError::EmptyField`] when the message is empty
    /// after trimming whitespace.
    pub fn error(error: impl Into<Box<str>>) -> Result<Self, SidecarContractError> {
        Ok(Self::Error {
            error: SidecarErrorMessage::new(error)?,
        })
    }

    /// Returns the sidecar frame type.
    ///
    /// # Examples
    ///
    /// ```
    /// use opencode_desktop::SidecarEvent;
    ///
    /// assert_eq!(SidecarEvent::stopped().event_type(), "stopped");
    /// ```
    #[must_use]
    pub const fn event_type(&self) -> &'static str {
        match self {
            Self::Ready { .. } => "ready",
            Self::Sqlite { .. } => "sqlite",
            Self::Stopped => "stopped",
            Self::Error { .. } => "error",
        }
    }
}

fn require_non_empty(
    field: &'static str,
    value: Box<str>,
) -> Result<Box<str>, SidecarContractError> {
    if value.trim().is_empty() {
        return Err(SidecarContractError::EmptyField { field });
    }

    Ok(value)
}

#[cfg(test)]
mod tests {
    use super::{InitStep, MigrationProgress, ServerReadyData, SidecarContractError, SidecarEvent};
    use std::error::Error;

    #[test]
    fn ready_event_serializes_with_expected_shape() -> Result<(), Box<dyn Error>> {
        // Tests the desktop ready event JSON contract with a local sidecar URL,
        // sample Basic Auth credentials, and exact field assertions because
        // preload initialization consumes this payload shape.
        let event = SidecarEvent::ready(ServerReadyData::new(
            "http://127.0.0.1:4096",
            "opencode",
            "secret",
        )?);

        let value = serde_json::to_value(event)?;

        assert_eq!(value["type"], "ready");
        assert_eq!(value["data"]["url"], "http://127.0.0.1:4096");
        assert_eq!(value["data"]["username"], "opencode");
        assert_eq!(value["data"]["password"], "secret");
        Ok(())
    }

    #[test]
    fn debug_output_redacts_ready_password() -> Result<(), Box<dyn Error>> {
        // Tests Debug redaction for ServerReadyData using a known password and
        // string containment assertions because desktop logs may include this
        // value during sidecar troubleshooting.
        let event = SidecarEvent::ready(ServerReadyData::new(
            "http://127.0.0.1:4096",
            "opencode",
            "secret",
        )?);

        let debug = format!("{event:?}");

        assert!(debug.contains("<redacted>"));
        assert!(!debug.contains("secret"));
        Ok(())
    }

    #[test]
    fn ready_payload_deserialize_rejects_empty_password() {
        // Tests ServerReadyData deserialization with an empty password field,
        // JSON input at the sidecar boundary, and an error assertion because
        // serde must not bypass constructor validation.
        let result = serde_json::from_str::<ServerReadyData>(
            r#"{"url":"http://127.0.0.1:4096","username":"opencode","password":""}"#,
        );

        assert!(result.is_err());
    }

    #[test]
    fn error_event_serializes_and_rejects_empty_messages() -> Result<(), Box<dyn Error>> {
        // Tests sidecar error event validation with one valid message and one
        // empty JSON message because Electron-side diagnostics must not accept
        // blank error frames at the process boundary.
        let event = SidecarEvent::error("startup failed")?;
        let value = serde_json::to_value(event)?;
        let empty_result = serde_json::from_str::<SidecarEvent>(r#"{"type":"error","error":""}"#);

        assert_eq!(value["type"], "error");
        assert_eq!(value["error"], "startup failed");
        assert!(empty_result.is_err());
        Ok(())
    }

    #[test]
    fn migration_progress_rejects_values_above_one_hundred() {
        // Tests MigrationProgress validation with the first invalid percentage,
        // no external input, and a semantic error assertion because renderer
        // progress bars must stay in the 0..=100 range.
        let result = MigrationProgress::try_from(101);

        assert_eq!(result, Err(SidecarContractError::ProgressOutOfRange));
    }

    #[test]
    fn sqlite_event_deserialize_rejects_progress_above_one_hundred() {
        // Tests sidecar SQLite event deserialization with an invalid progress
        // percentage, JSON input at the sidecar boundary, and an error
        // assertion because serde must preserve constructor validation.
        let result = serde_json::from_str::<SidecarEvent>(r#"{"type":"sqlite","progress":101}"#);

        assert!(result.is_err());
    }

    #[test]
    fn init_step_uses_preload_labels() {
        // Tests InitStep wire labels from the preload contract, fixed enum
        // inputs, and exact label assertions because Electron event names are
        // stringly typed at the process boundary.
        assert_eq!(InitStep::ServerWaiting.as_str(), "server_waiting");
        assert_eq!(InitStep::SqliteWaiting.as_str(), "sqlite_waiting");
        assert_eq!(InitStep::Done.as_str(), "done");
    }
}
